import { API_BASE_URL } from '../config';
import { normalizeResponseErrors } from './utils';

//FETCH PLAYERS
export const FETCH_PLAYERS_REQUEST = 'FETCH_PLAYERS_REQUEST';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const FETCH_PLAYERS_ERROR = 'FETCH_PLAYERS_ERROR';

//FETCH USER PLAYERS
export const FETCH_USER_PLAYERS_REQUEST = 'FETCH_USER_PLAYERS_REQUEST';
export const FETCH_USER_PLAYERS_SUCCESS = 'FETCH_USER_PLAYERS_SUCCESS';
export const FETCH_USER_PLAYERS_ERROR = 'FETCH_USER_PLAYERS_ERROR';

//FETCH USER PLAYERS BY POSITION
export const FETCH_USER_PLAYERS_BY_POSITION_REQUEST = 'FETCH_USER_PLAYERS_BY_POSITION_REQUEST';
export const FETCH_USER_PLAYERS_BY_POSITION_SUCCESS = 'FETCH_USER_PLAYERS_BY_POSITION_SUCCESS';
export const FETCH_USER_PLAYERS_BY_POSITION_ERROR = 'FETCH_USER_PLAYERS_BY_POSITION_ERROR';

//FETCH CURRENT PLAYER
export const FETCH_CURRENT_PLAYER_REQUEST = 'FETCH_CURRENT_PLAYER_REQUEST';
export const FETCH_CURRENT_PLAYER_SUCCESS = 'FETCH_CURRENT_PLAYER_SUCCESS';
export const FETCH_CURRENT_PLAYER_ERROR = 'FETCH_CURRENT_PLAYER_ERROR';

//CLEAR CURRENT PLAYER
export const CLEAR_CURRENT_PLAYER_REQUEST = 'CLEAR_CURRENT_PLAYER_REQUEST';
export const CLEAR_CURRENT_PLAYER_SUCCESS = 'CLEAR_CURRENT_PLAYER_SUCCESS';
export const CLEAR_CURRENT_PLAYER_ERROR = 'CLEAR_CURRENT_PLAYER_ERROR';

//ADD PLAYER TO USER
export const ADD_PLAYER_TO_USER_REQUEST = 'ADD_PLAYER_TO_USER_REQUEST';
export const ADD_PLAYER_TO_USER_SUCCESS = 'ADD_PLAYER_TO_USER_SUCCESS';
export const ADD_PLAYER_TO_USER_ERROR = 'ADD_PLAYER_TO_USER_ERROR';

//REMOVE PLAYER FROM USER
export const REMOVE_PLAYER_FROM_USER_REQUEST = 'REMOVE_PLAYER_FROM_USER_REQUEST';
export const REMOVE_PLAYER_FROM_USER_SUCCESS = 'REMOVE_PLAYER_FROM_USER_SUCCESS';
export const REMOVE_PLAYER_FROM_USER_ERROR = 'REMOVE_PLAYER_FROM_USER_ERROR';

//ADD COMMENT TO PLAYER
export const ADD_COMMENT_TO_PLAYER_REQUEST = 'ADD_COMMENT_TO_PLAYER_REQUEST';
export const ADD_COMMENT_TO_PLAYER_SUCCESS = 'ADD_COMMENT_TO_PLAYER_SUCCESS';
export const ADD_COMMENT_TO_PLAYER_ERROR = 'ADD_COMMENT_TO_PLAYER_ERROR';

//REMOVE COMMENT FROM PLAYER
export const REMOVE_COMMENT_FROM_PLAYER_REQUEST = 'REMOVE_COMMENT_FROM_PLAYER_REQUEST';
export const REMOVE_COMMENT_FROM_PLAYER_SUCCESS = 'REMOVE_COMMENT_FROM_PLAYER_SUCCESS';
export const REMOVE_COMMENT_FROM_PLAYER_ERROR = 'REMOVE_COMMENT_FROM_PLAYER_ERROR';

//CREATE PLAYER
export const CREATE_PLAYER_REQUEST = 'CREATE_PLAYER_REQUEST';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_ERROR = 'CREATE_PLAYER_ERROR';

//EDIT PLAYER
export const EDIT_PLAYER_REQUEST = 'EDIT_PLAYER_REQUEST';
export const EDIT_PLAYER_SUCCESS = 'EDIT_PLAYER_SUCCESS';
export const EDIT_PLAYER_ERROR = 'EDIT_PLAYER_ERROR';